<?php

namespace Database\Seeders;

use App\Models\Amenity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AmenitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $amenities = [
            [
                'name' => 'Garden view',
                'display_amenities_order' => 1,
                'media_id' => 15,
                'media_name' => 'Garden view',
                'media_css' => 'Garden view-ur',
                'amenities_categories_id' => 1,
            ],
            [
                'name' => 'Courtyard view',
                'display_amenities_order' => 2,
                'media_id' => 15,
                'media_name' => 'Garden view',
                'media_css' => 'Garden view-ur',
                'amenities_categories_id' => 1,
            ],
            [
                'name' => 'Park view',
                'display_amenities_order' => 3,
                'media_id' => 15,
                'media_name' => 'Garden view',
                'media_css' => 'Garden view-ur',
                'amenities_categories_id' => 1,
            ],
            [
                'name' => 'Hair dryer',
                'display_amenities_order' => 4,
                'media_id' => 16,
                'media_name' => 'Hair dryer',
                'media_css' => 'Hair dryer-ur',
                'amenities_categories_id' => 2,
            ],
            [
                'name' => 'Cleaning products',
                'display_amenities_order' => 5,
                'media_id' => 17,
                'media_name' => 'Cleaning products',
                'media_css' => 'Cleaning products-ur',
                'amenities_categories_id' => 2,
            ],
            [
                'name' => 'Conditioner',
                'display_amenities_order' => 6,
                'media_id' => 18,
                'media_name' => 'Conditioner',
                'media_css' => 'Conditioner-ur',
                'amenities_categories_id' => 2,
            ],
            [
                'name' => 'liquid-soap',
                'display_amenities_order' => 7,
                'media_id' => 19,
                'media_name' => 'liquid-soap',
                'media_css' => 'liquid-soap-ur',
                'amenities_categories_id' => 2,
            ],
            [
                'name' => 'Hot water',
                'display_amenities_order' => 8,
                'media_id' => 20,
                'media_name' => 'Hot water',
                'media_css' => 'Hot water-ur',
                'amenities_categories_id' => 2,
            ],
            [
                'name' => 'Shower gel',
                'display_amenities_order' => 9,
                'media_id' => 19,
                'media_name' => 'liquid-soap',
                'media_css' => 'liquid-soap-ur',
                'amenities_categories_id' => 2,
            ],
            [
                'name' => 'Essentials',
                'display_amenities_order' => 10,
                'media_id' => 21,
                'media_name' => 'Essentials',
                'media_css' => 'Essentials-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Hangers',
                'display_amenities_order' => 11,
                'media_id' => 22,
                'media_name' => 'Hangers',
                'media_css' => 'Hangers-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Bed linen',
                'display_amenities_order' => 12,
                'media_id' => 23,
                'media_name' => 'Bed linen',
                'media_css' => 'Bed linen-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Extra pillows and blankets',
                'display_amenities_order' => 13,
                'media_id' => 24,
                'media_name' => 'Extra pillows and blankets',
                'media_css' => 'Extra pillows and blankets-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Room-darkening blinds',
                'display_amenities_order' => 14,
                'media_id' => 25,
                'media_name' => 'Room-darkening blinds',
                'media_css' => 'Room-darkening blinds-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Iron',
                'display_amenities_order' => 15,
                'media_id' => 26,
                'media_name' => 'Iron',
                'media_css' => 'Iron-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Clothes drying rack',
                'display_amenities_order' => 16,
                'media_id' => 22,
                'media_name' => 'Hangers',
                'media_css' => 'Hangers-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Clothes storage',
                'display_amenities_order' => 17,
                'media_id' => 27,
                'media_name' => 'Clothes storage',
                'media_css' => 'Clothes storage-ur',
                'amenities_categories_id' => 3,
            ],
            [
                'name' => 'Ethernet connection',
                'display_amenities_order' => 18,
                'media_id' => 28,
                'media_name' => 'Ethernet connection',
                'media_css' => 'Ethernet connection-ur',
                'amenities_categories_id' => 14,
            ],
            [
                'name' => 'Exercise equipment & yoga mat',
                'display_amenities_order' => 19,
                'media_id' => 29,
                'media_name' => 'Exercise equipment & yoga mat',
                'media_css' => 'Exercise equipment & yoga mat-ur',
                'amenities_categories_id' => 14,
            ],
            [
                'name' => 'Books and reading material',
                'display_amenities_order' => 20,
                'media_id' => 30,
                'media_name' => 'Books and reading material',
                'media_css' => 'Books and reading material-ur',
                'amenities_categories_id' => 14,
            ],
            [
                'name' => 'Outdoor playground',
                'display_amenities_order' => 21,
                'media_id' => 31,
                'media_name' => 'Outdoor playground',
                'media_css' => 'Outdoor playground-ur',
                'amenities_categories_id' => 4,
            ],
            [
                'name' => 'Air conditioning',
                'display_amenities_order' => 22,
                'media_id' => 32,
                'media_name' => 'Air conditioning',
                'media_css' => 'Air conditioning-ur',
                'amenities_categories_id' => 5,
            ],
            [
                'name' => 'Ceiling fan',
                'display_amenities_order' => 23,
                'media_id' => 33,
                'media_name' => 'Ceiling fan',
                'media_css' => 'Ceiling fan-ur',
                'amenities_categories_id' => 5,
            ],
            [
                'name' => 'Portable fans',
                'display_amenities_order' => 24,
                'media_id' => 34,
                'media_name' => 'Portable fans',
                'media_css' => 'Portable fans-ur',
                'amenities_categories_id' => 5,
            ],
            [
                'name' => 'Portable heater',
                'display_amenities_order' => 25,
                'media_id' => 35,
                'media_name' => 'Portable heater',
                'media_css' => 'Portable heater-ur',
                'amenities_categories_id' => 5,
            ],
            [
                'name' => 'Exterior security cameras on property',
                'display_amenities_order' => 26,
                'media_id' => 36,
                'media_name' => 'Exterior security cameras on property',
                'media_css' => 'Exterior security cameras on property-ur',
                'amenities_categories_id' => 6,
            ],
            [
                'name' => 'Fire Extinguisher',
                'display_amenities_order' => 27,
                'media_id' => 37,
                'media_name' => 'Fire extinguisher',
                'media_css' => 'Fire extinguisher-ur',
                'amenities_categories_id' => 6,
            ],
            [
                'name' => 'First Aid Kit',
                'display_amenities_order' => 28,
                'media_id' => 38,
                'media_name' => 'First aid kit',
                'media_css' => 'First aid kit-ur',
                'amenities_categories_id' => 6,
            ],
            [
                'name' => 'Wifi',
                'display_amenities_order' => 29,
                'media_id' => 39,
                'media_name' => 'Wifi',
                'media_css' => 'Wifi-ur',
                'amenities_categories_id' => 7,
            ],
            [
                'name' => 'Dedicated workspace',
                'display_amenities_order' => 30,
                'media_id' => 40,
                'media_name' => 'Dedicated workspace',
                'media_css' => 'Dedicated workspace-ur',
                'amenities_categories_id' => 7,
            ],
            [
                'name' => 'Kitchen',
                'display_amenities_order' => 31,
                'media_id' => 41,
                'media_name' => 'Kitchen',
                'media_css' => 'Kitchen-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Fridge',
                'display_amenities_order' => 32,
                'media_id' => 42,
                'media_name' => 'Fridge',
                'media_css' => 'Fridge-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Cooking basics',
                'display_amenities_order' => 33,
                'media_id' => 43,
                'media_name' => 'Cooking basics',
                'media_css' => 'Cooking basics-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Dishes and cutlery',
                'display_amenities_order' => 34,
                'media_id' => 44,
                'media_name' => 'Dishes and cutlery',
                'media_css' => 'Dishes and cutlery-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Freezer',
                'display_amenities_order' => 35,
                'media_id' => 42,
                'media_name' => 'Fridge',
                'media_css' => 'Fridge-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Stainless steel cooker',
                'display_amenities_order' => 36,
                'media_id' => 45,
                'media_name' => 'Stainless steel cooker',
                'media_css' => 'Stainless steel cooker-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Oven',
                'display_amenities_order' => 37,
                'media_id' => 46,
                'media_name' => 'Oven',
                'media_css' => 'Oven-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Kettle',
                'display_amenities_order' => 38,
                'media_id' => 47,
                'media_name' => 'Kettle',
                'media_css' => 'Kettle-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Coffee maker',
                'display_amenities_order' => 39,
                'media_id' => 48,
                'media_name' => 'Coffee maker',
                'media_css' => 'Coffee maker-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Baking sheet',
                'display_amenities_order' => 40,
                'media_id' => 49,
                'media_name' => 'Baking sheet',
                'media_css' => 'Baking sheet-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Blender',
                'display_amenities_order' => 41,
                'media_id' => 50,
                'media_name' => 'Blender',
                'media_css' => 'Blender-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Dining table',
                'display_amenities_order' => 42,
                'media_id' => 51,
                'media_name' => 'Dining table',
                'media_css' => 'Dining table-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Coffee',
                'display_amenities_order' => 43,
                'media_id' => 48,
                'media_name' => 'Coffee maker',
                'media_css' => 'Coffee maker-ur',
                'amenities_categories_id' => 8,
            ],
            [
                'name' => 'Private entrance',
                'display_amenities_order' => 44,
                'media_id' => 52,
                'media_name' => 'Private entrance',
                'media_css' => 'Private entrance-ur',
                'amenities_categories_id' => 9,
            ],
            [
                'name' => 'Private patio or balcony',
                'display_amenities_order' => 45,
                'media_id' => 53,
                'media_name' => 'Private patio or balcony',
                'media_css' => 'Private patio or balcony-ur',
                'amenities_categories_id' => 10,
            ],
            [
                'name' => 'Shared back garden',
                'display_amenities_order' => 46,
                'media_id' => 1,
                'media_name' => 'Scenic views',
                'media_css' => 'Scenic views-ur',
                'amenities_categories_id' => 10,
            ],
            [
                'name' => 'Outdoor furniture',
                'display_amenities_order' => 47,
                'media_id' => 54,
                'media_name' => 'Outdoor furniture',
                'media_css' => 'Outdoor furniture-ur',
                'amenities_categories_id' => 10,
            ],
            [
                'name' => 'Outdoor dining area',
                'display_amenities_order' => 48,
                'media_id' => 54,
                'media_name' => 'Outdoor furniture',
                'media_css' => 'Outdoor furniture-ur',
                'amenities_categories_id' => 10,
            ],
            [
                'name' => 'Free parking on premises',
                'display_amenities_order' => 49,
                'media_id' => 55,
                'media_name' => 'Free parking on premises',
                'media_css' => 'Free parking on premises-ur',
                'amenities_categories_id' => 11,
            ],
            [
                'name' => 'Free on-street parking',
                'display_amenities_order' => 50,
                'media_id' => 55,
                'media_name' => 'Free parking on premises',
                'media_css' => 'Free parking on premises-ur',
                'amenities_categories_id' => 11,
            ],
            [
                'name' => 'Self check-in',
                'display_amenities_order' => 51,
                'media_id' => 56,
                'media_name' => 'Self check-in',
                'media_css' => 'Self check-in-ur',
                'amenities_categories_id' => 12,
            ],
            [
                'name' => 'Smart lock',
                'display_amenities_order' => 52,
                'media_id' => 57,
                'media_name' => 'Smart lock',
                'media_css' => 'Smart lock-ur',
                'amenities_categories_id' => 12,
            ],
            [
                'name' => 'Housekeeping available every day',
                'display_amenities_order' => 53,
                'media_id' => 58,
                'media_name' => 'Housekeeping available every day',
                'media_css' => 'Housekeeping available every day-ur',
                'amenities_categories_id' => 12,
            ],
        ];

        foreach ($amenities as $amenity) {
            Amenity::create($amenity);
        }
    }
}
