<?php

namespace App\Http\Requests\Admin\FeaturedProperty;

use Illuminate\Foundation\Http\FormRequest;

class CancelFeaturedPropertyRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'cancellation_reason' => [
                'nullable',
                'string',
                'max:1000',
            ],

            /*
             * Audit/status values are generated by backend.
             */
            'status' => [
                'prohibited',
            ],

            'cancelled_by' => [
                'prohibited',
            ],

            'cancelled_at' => [
                'prohibited',
            ],
        ];
    }
}