<?php

namespace App\Http\Requests\Admin\FeaturedProperty;

use Illuminate\Foundation\Http\FormRequest;

class StoreFeaturedPropertyRequest extends FormRequest
{
    public function authorize(): bool
    {
        /*
         * Permission middleware will be added at route/controller level.
         */
        return true;
    }

    public function rules(): array
    {
        return [
            'dynamic_post_id' => [
                'required',
                'integer',
                'exists:dynamic_posts,id',
            ],

            /*
             * Nullable because service will use now()
             * when starts_at is not provided.
             */
            'starts_at' => [
                'nullable',
                'date',
            ],

            'ends_at' => [
                'required',
                'date',
                'after:starts_at',
            ],

            'priority' => [
                'nullable',
                'integer',
                'min:0',
                'max:100000',
            ],

            'admin_notes' => [
                'nullable',
                'string',
                'max:1000',
            ],

            /*
             * These values must always be generated by backend.
             */
            'source' => [
                'prohibited',
            ],

            'status' => [
                'prohibited',
            ],

            'created_by' => [
                'prohibited',
            ],

            'updated_by' => [
                'prohibited',
            ],

            'cancelled_by' => [
                'prohibited',
            ],

            'cancelled_at' => [
                'prohibited',
            ],
        ];
    }

    public function messages(): array
    {
        return [
            'dynamic_post_id.required' =>
                'Please select a property.',

            'dynamic_post_id.exists' =>
                'Selected property does not exist.',

            'ends_at.required' =>
                'Featured end date is required.',

            'ends_at.after' =>
                'Featured end date must be after the start date.',

            'priority.min' =>
                'Priority cannot be negative.',

            'priority.max' =>
                'Priority may not be greater than 100000.',
        ];
    }
}