<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('property_listing_revisions', function (Blueprint $table) {
            $table->id();

            $table->foreignId('dynamic_post_id')
                ->constrained('dynamic_posts')
                ->cascadeOnDelete();

            $table->unsignedInteger('version');

            // initial_submission | resubmission | live_update
            $table->string('source', 50);

            // under_review | resubmission | assigned | in_verification | approved | rejected
            $table->string('status', 50)->index();

            /*
             * baseline_payload:
             * The last approved version before a live property was edited.
             *
             * submitted_payload:
             * The complete version submitted for verification.
             *
             * LONGTEXT is used because a complete property snapshot may contain
             * custom fields, taxonomies, relationships and media references.
             */
            $table->longText('baseline_payload')->nullable();
            $table->longText('submitted_payload');

            $table->foreignId('submitted_by')
                ->constrained('users')
                ->cascadeOnDelete();

            $table->timestamp('submitted_at');

            $table->foreignId('assigned_to')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->foreignId('assigned_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->timestamp('assigned_at')->nullable();
            $table->timestamp('verification_started_at')->nullable();

            $table->foreignId('decided_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->timestamp('decided_at')->nullable();
            $table->text('rejection_reason')->nullable();

            $table->timestamps();

            $table->unique(
                ['dynamic_post_id', 'version'],
                'property_revision_version_unique'
            );

            $table->index(
                ['status', 'assigned_to'],
                'property_revision_status_assignee_index'
            );
        });

        Schema::create('property_verification_events', function (Blueprint $table) {
            $table->id();

            $table->foreignId('dynamic_post_id')
                ->constrained('dynamic_posts')
                ->cascadeOnDelete();

            $table->foreignId('revision_id')
                ->nullable()
                ->constrained('property_listing_revisions')
                ->cascadeOnDelete();

            // Null actor means the event was generated by the system.
            $table->foreignId('actor_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->string('event', 100)->index();
            $table->string('from_status', 50)->nullable();
            $table->string('to_status', 50)->nullable();
            $table->text('message')->nullable();
            $table->json('metadata')->nullable();
            $table->timestamp('created_at')->useCurrent();

            $table->index(
                ['dynamic_post_id', 'created_at'],
                'property_event_timeline_index'
            );
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('property_verification_events');
        Schema::dropIfExists('property_listing_revisions');
    }
};
